
// Indian Food Classes
export const YOLO_CLASSES = [
  'adhirasam',
  'aloo gobi',
  'aloo matar',
  'aloo methi',
  'aloo shimla mirch',
  'aloo tikki',
  'anarsa',
  'appe',
  'ariselu',
  'baati',
  'bandar laddu',
  'basundi',
  'bhatura',
  'bhindi masala',
  'biryani',
  'boondi',
  'butter chicken',
  'chak hao kheer',
  'cham cham',
  'chana masala',
  'chapati',
  'chicken rezala',
  'chicken tikka',
  'chicken tikka masala',
  'chikki',
  'churma',
  'daal',
  'daal puri',
  'dal makhani',
  'dal tadka',
  'dharwad pedha',
  'doodhpak',
  'double ka meetha',
  'dum aloo',
  'gajar halwa',
  'gavvalu',
  'ghevar',
  'gujia',
  'gulab jamun',
  'imarti',
  'jalebi',
  'kachori',
  'kadai paneer',
  'kadhi pakoda',
  'kakinada khaja',
  'kalakand',
  'karela bharta',
  'kheer',
  'kofta',
  'lassi',
  'ledikeni',
  'litti chokha',
  'lyangcha',
  'maach jhol',
  'makki di roti sarso ka saag',
  'malpua',
  'misi roti',
  'misti doi',
  'modak',
  'mysore pak',
  'naan',
  'navrattan korma',
  'palak paneer',
  'paneer butter masala',
  'phirni',
  'pithe',
  'poha',
  'poornalu',
  'pootharekulu',
  'qubani ka meetha',
  'rabri',
  'ras malai',
  'rasgulla',
  'sandesh',
  'shankarpali',
  'sheera',
  'shrikhand',
  'soan papdi',
  'sohan halwa',
  'sutar feni',
  'unni appam'
];
